### ISSUE TITLE
Macro Trouble Compiling?

### ISSUE THREAD

**Issue by kentborg** [erickt/rust-zmq#123]
When trying to build I am getting this error (repeated 20 times, though it says something about there being "42 previous errors"):

> src/lib.rs:27:20: 27:23 error: expected expression, found `unsafe`
> src/lib.rs:27         let rc = $($tt)*;
>                                  ^~~

(That `^` should be pointing at the `$tt`, but I couldn't figure out how to format that spacing...)

Suggestions? I am at d473b20e08, maybe backup to an earlier commit?

Thanks,

-kb

**Comment by rotty** [comment]
What version of Rust are you using? As you can see at <https://travis-ci.org/erickt/rust-zmq/branches>, current master should build with current stable, beta and nightly compilers.

**Comment by kentborg** [comment]
Um, kinda old. I knew I should update it, but my Debian Cmake is too old...guess I need to uninstall my self-built version and install something more standard.

Let me try that.

Thanks,

-kb

**Comment by rotty** [comment]
As this almost certainly due to an outdated Rust installation, I'll close this.

**Comment by kentborg** [comment]
Indeed, when I switched to using rustup and that latest stable, it compiles.

Thanks,

-kb
