### ISSUE TITLE
Track down Windows/Appveyor test failures

### ISSUE THREAD

**Issue by erickt** [erickt/rust-zmq#125]
We managed to get our zeromq tests partially passing on Windows, but we still need some help tracking down why 5 of our tests are [timing out](https://ci.appveyor.com/project/erickt/rust-zmq). We need this before we can say we officially support Windows. @tcosprojects / @pfernie / @Ginurx, you've all opened tickets/pull requests to get this crate to work on Windows, any chance you could help us track down what's going on in these tests?

**Comment by pfernie** [comment]
I ran these tests and got the same failures as on Appveyor; what look to be "TimedOut" events on 5 tests:
test_exchanging_{bytes,messages,multipart,strings} and test_polling

The TimedOut status on Appveyor is misleading; looking back through the Appveyor log, for example:
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable', ../src/libcore\result.rs:837
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable', ../src/libcore\result.rs:837```

If I switch out the unwrap()s in those tests w/ expects, I actually get failures on the first recv_*.expect() call in each, with error "Resource temporarily unavailable". So, my first guess is this is a mis-mapping of EAGAIN which should be signaling a retry? I unfortunately don't have time to dig deeper, but hopefully that is a useful starting point...

Also, the test_exchanging_bytes test looks to erroneously have a nested called to timeout_ms?

**Comment by erickt** [comment]
Thanks @pfernie! I fixed the redundant call to `timeout_ms` in #127. Those EAGAIN might be coming from the timeouts I added in https://github.com/erickt/rust-zmq/blob/master/tests/test.rs#L15, so they might be legitimate.

**Comment by pfernie** [comment]
I had some time to look at this; [PR 140]:https://github.com/erickt/rust-zmq/pull/140 fixes 4/5 failures on my local windows machine. ``test_polling`` is still a failure; hopefully I have a little more time to look at it.

**Comment by rotty** [comment]
@pfernie Just a hunch regarding `test_polling`: the test uses an in-process `tcp` socket from the same thread; I'm not sure if this is (documentedly) supported at all; maybe try switching to `inproc` or using two threads would help? 

The `test_disconnect_inproc.c` in libzmq uses a single thread with `zmq_poll`, but with `inproc` sockets, and presumably works on Windows as well.

**Comment by rotty** [comment]
Thanks to @pfernie, this is now fixed!
