### ISSUE TITLE
zmq version

### ISSUE THREAD

**Issue by kpp** [erickt/rust-zmq#177]
In docs it is said that rust-zmq requires ZeroMQ **3.2** or newer, however it requires **4.1** or newer. There is a problem linking `zmq_has` function, which appears only in [4.1 version](http://api.zeromq.org/4-1:_start). 

see:  https://docs.rs/crate/zmq/0.8.1/builds/44848

**Comment by kpp** [comment]
In my project I fixed that with
```
[dependencies.zmq]
version = "0.8"
default-features = false
```

Should't feature `zmq_has` be disabled by default?

**Comment by rotty** [comment]
@kpp I don't think so, I'll address this via adjusting the documentation accordingly. Thanks for exposing this issue.

**Comment by vimmerru** [comment]
I have the same issue on any RHEL based repo with EPEL. It is better to avoid features like this by default.
