### ISSUE TITLE
Can't crosscompile rust-zmq

### ISSUE THREAD

**Issue by simias** [erickt/rust-zmq#179]
`zmq` has `zmq-sys` as a build dependency. It uses it in `build.rs` to dynamically test for the supported features.

This can't work if you're cross-compiling the crate (for an ARM target in my case) because you can't execute anything on the host.

For this situation it would be nice to have an other way to provide the build system with the supported features, for instance in an environment variable or maybe a feature flag? I'm not really sure. At any rate I don't know how to handle optional build dependencies in the Cargo.toml, because if cargo tries to build the host zmq-sys as a build dependency while cross-compiling it will invariably fail.

**Comment by rotty** [comment]
See also PR #177; does the suggested use of `default-features = false` help for cross-compiling?

I agree for cross-compiling we want a way to avoid dynamically testing for features; I think an environment variable would be a good fit, as there's already `LIBZMQ_LIB_DIR` and friends, which are similiar in purpose.

**Comment by simias** [comment]
Unfortunately it doesn't. The error occurs "early", when cargo tries to build zmq-sys for the `build-dependencies`. I set `LIBZMQ_PREFIX` in the environment to point at the ARM version of the library, but then the host (x86-64) version tries to link against that and obviously it doesn't work.

At first I thought about tweaking the zmq-sys build.rs to get the host version of libzmq when building the native version, but I then realized that it was absurd, it would make the zmq build script use the host lib capabilities to decide what's supported in the cross-compiled version, which makes no sense.

For now I think I'm going to fork the code to remove the build dependency on zmq-sys and hardcode the capabilities in the build.rs script. I can't think of a better way to handle this situation.

FYI the python zeromq bindings have the same issue, they use a runtime test to get the version of the library. You have to patch it when cross compiling.

**Comment by mikelodder7** [comment]
You can use my fork of this crate at https://github.com/mikelodder7/rust-zmq-mobile. I'm using to cross compile stuff for Android.

**Comment by simias** [comment]
Ah yeah, I should have updated this issue, I ended up doing the same thing (albeit using a slightly more heavy-handed approach): https://github.com/simias/rust-zmq/commit/56119dd1b6808161539d87afb657f5197bf30d3f

**Comment by skrap** [comment]
My pull request #247 removes the build.rs in favor of weak linking the required symbols, allowing zmq to cross-compile cleanly.

**Comment by rotty** [comment]
@simias: I can cross-compile (both current `release/v0.8` and `master`) from Linux to both `x86_64-pc-windows-gnu` and `i686-pc-windows-gnu`, but that may be just because I have an installation of libzmq on the host. Here is my command-line:

```
 PKG_CONFIG_PATH=$HOME/.local-w32/lib/pkgconfig PKG_CONFIG_ALLOW_CROSS=1 cargo build --target=i686-pc-windows-gnu
```

I'd appreciate information about what commands you are running, and what *exact* error messages you are getting.

**Comment by rotty** [comment]
Indeed, cross-compilation failed when not having a host installation of libzmq. In particular, linking fails when building `zmq`:

```
...
  = note: /usr/bin/ld: cannot find -lzmq
          collect2: error: ld returned 1 exit status

error: aborting due to previous error

error: Could not compile `zmq`.
```

**Comment by rotty** [comment]
@mikelodder7 I removed feature-probing in rust-zmq now as well, see commit ed5fd6de and issue #275 for the rationale; I guess this should allow you to use rust-zmq instead of your fork -- should any issues regarding cross compilation remain, I'd appreciate bug reports!
