### ISSUE TITLE
SIGINT has been caught, but get unknown error [4]: Interrupted system call

### ISSUE THREAD

**Issue by zwb-ict** [erickt/rust-zmq#191]
I catch SIGINT at signal handler function, but at runtime I run CTRL+C, get panic:

> ^Cthread 'main' panicked at 'unknown error [4]: Interrupted system call', /home/zwb/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.1/src/lib.rs:307

with ```RUST_BACKTRACE=1 target/release/interrupt``` get:

> stack backtrace:
>    0: std::sys:: imp::backtrace::tracing:: imp::unwind_backtrace
>              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1: std::sys_common::backtrace::_print
>              at /checkout/src/libstd/sys_common/backtrace.rs:71
>    2: std::panicking::default_hook::{{closure}}
>              at /checkout/src/libstd/sys_common/backtrace.rs:60
>              at /checkout/src/libstd/panicking.rs:355
>    3: std::panicking::default_hook
>              at /checkout/src/libstd/panicking.rs:371
>    4: std::panicking::rust_panic_with_hook
>              at /checkout/src/libstd/panicking.rs:549
>    5: std::panicking::begin_panic
>              at /checkout/src/libstd/panicking.rs:511
>    6: std::panicking::begin_panic_fmt
>              at /checkout/src/libstd/panicking.rs:495
>    7: zmq::Error::from_raw
>    8: zmq::poll
>    9: interrupt::main
>   10: __rust_maybe_catch_panic
>              at /checkout/src/libpanic_unwind/lib.rs:98
>   11: std::rt::lang_start
>              at /checkout/src/libstd/panicking.rs:433
>              at /checkout/src/libstd/panic.rs:361
>              at /checkout/src/libstd/rt.rs:59
>   12: __libc_start_main
>   13: _start

the code:

``` rust
extern crate nix;
extern crate zmq;

use std::io::{self, Write};
// use std::os::raw::c_void;
use std::os::unix::io::RawFd;
use std::process;
use nix::sys::signal;

static mut S_FD: RawFd = -1;

extern "C" fn s_signal_handler(_: i32) {
    let rc = unsafe { nix::unistd::write(S_FD, b" ") };
    match rc {
        Ok(_) => {}
        Err(_) => {
            println!("Error while writing to self-pipe.");
            let _ = io::stdout().flush();
        }
    }
}

fn s_catch_signals(fd: RawFd) {
    unsafe {
        S_FD = fd;
    }

    let sig_action = signal::SigAction::new(signal::SigHandler::Handler(s_signal_handler),
                                            signal::SaFlags::empty(),
                                            signal::SigSet::empty());
    unsafe {
        signal::sigaction(signal::SIGINT, &sig_action).unwrap();
        signal::sigaction(signal::SIGTERM, &sig_action).unwrap();
    }
}

fn main() {
    let context = zmq::Context::new();
    let socket = context.socket(zmq::REP).unwrap();
    assert!(socket.bind("tcp://*:5555").is_ok());

    let pipefds = nix::unistd::pipe().unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_GETFL).unwrap();
    nix::fcntl::fcntl(pipefds.0, nix::fcntl::F_SETFL(nix::fcntl::O_NONBLOCK)).unwrap();

    // let pipefds0_ptr: *mut RawFd = &mut pipefds.0;
    // let pipefds0 = unsafe { zmq::Socket::from_raw(pipefds0_ptr as *mut c_void) };

    s_catch_signals(pipefds.1);

    // let items = &mut [pipefds0.as_poll_item(zmq::POLLIN),
    //                   socket.as_poll_item(zmq::POLLIN)];

    let items = &mut [zmq::PollItem::from_fd(pipefds.0),
                      socket.as_poll_item(zmq::POLLIN)];
    loop {
        let rc = zmq::poll(items, -1);
        match rc {
            Ok(v) => {
                assert!(v >= 0);
                if v == 0 {
                    continue;
                }
                if items[0].is_readable() {
                    let buffer = &mut [0; 1];
                    nix::unistd::read(pipefds.0, buffer).unwrap();
                    println!("W: interrupt received, killing server...");
                    break;
                }
                if items[1].is_readable() {
                    let buffer = &mut [0; 255];
                    let rc = socket.recv_into(buffer, zmq::DONTWAIT);
                    match rc {
                        Ok(_) => println!("W: recv"),
                        Err(e) => {
                            if e == zmq::Error::EAGAIN || e == zmq::Error::EINTR {
                                continue;
                            }
                            println!("recv: {}", e);
                            process::exit(1);
                        }
                    }
                }
            }
            Err(e) => {
                if e == zmq::Error::EINTR {
                    continue;
                }
                println!("zmq::poll: {}", e);
                process::exit(1);
            }
        }
    }
}
```

and I'm sure ```s_signal_handler``` has been called(when Ctrl+c).

**Comment by rotty** [comment]
What platform are you running on? This looks a bit like it may be related with #184.

**Comment by zwb-ict** [comment]
Thank you @rotty, macOS 10.12.6.  I debuged and found the master branch solved this, with 
```rust
errno::EINTR => Error::EINTR
```
, but this fix doesn't in 0.8.1, so when build with cargo, SIGINT cann't be handled corrent.

**Comment by zwb-ict** [comment]
@rotty And there is another problem, after I modify 0.8.1 only add 
```rust
errno::EINTR => Error::EINTR
```
The zmq::poll can return 1. But 
```rust
items[0].is_readable() 
```
is false, then I try to see 
```rust
items[0].get_revents() 
```
It returns 0.

It seems that poll with a pipe(changed to PollItem) cann't set flag correctly.

**Comment by rotty** [comment]
@zwb-ict I have now released v0.8.2, which should contain the fix for the EINTR issue; can you confirm that works for you? For the poll problem I can't quite follow, can you please open another issue and explain it in a bit more detail?

**Comment by zwb-ict** [comment]
@rotty. Great, update to 0.8.2 solved this problem! Thank you. I think this issue can close.

**Comment by gibsond** [comment]
I get this problem using v0.9, but only when I build a release: cargo build --release:

thread 'main' panicked at 'called Result::unwrap() on an Err value: Interrupted system call', src/libcore/result.rs:1009:5
stack backtrace:
0: std::sys::unix::backtrace::tracing:imp:unwind_backtrace
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::panicking::default_hook::{{closure}}
at src/libstd/sys_common/backtrace.rs:71
at src/libstd/sys_common/backtrace.rs:59
at src/libstd/panicking.rs:211
2: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:227
at src/libstd/panicking.rs:491
3: std::panicking::continue_panic_fmt
at src/libstd/panicking.rs:398
4: rust_begin_unwind
at src/libstd/panicking.rs:325
5: core::panicking::panic_fmt
at src/libcore/panicking.rs:95
6: core::result::unwrap_failed
7: es1800_zmqsubr::main
8: std::rt::lang_start::{{closure}}
9: main
10: __libc_start_main
11: _start
Aborted (core dumped)

It works fine with just cargo run, but I need release code.

Any thoughts?

**Comment by gibsond** [comment]
I apologize for the above message.  I don't understand why it worked for cargo build, but not for cargo build --release, however I 'fixed' the problem by changing:

let stuff = socket.recv_multipart(0).unwrap();

to:

 let mut stuff: Vec<Vec<u8>>;
 match socket.recv_multipart(0) {
            Ok(msg) => { stuff = msg; },
            Err(error) => { println!("zmq receive error: {:?}", error); stuff = vec![vec![24, 25, 26]]},
 };

where I properly catch the ctrl-c error zmq encounters and do not panic, but just print a message and allow the ctrl-c handler catch the ctrl-c as I wanted.
