### ISSUE TITLE
Support Monitor Sockets

### ISSUE THREAD

**Issue by peterschwarz** [erickt/rust-zmq#203]
Add support for the [zmq_socket_monitor](http://api.zeromq.org/3-2:zmq-socket-monitor) in 0.8 (and presumably 0.9 - hopefully against libzmq 4.x).

This feature is useful for detecting changes in the state of a socket and acting accordingly (e.g. if a connected server goes down and returns, a client may need to send an application-specific handshake again).

**Comment by peterschwarz** [comment]
Implementation of this against 0.8 is provided in PR #202

**Comment by rotty** [comment]
This should be fixed in 0.8.3 and 0.9.0, as PR #202 is part of both of these releases.
