### ISSUE TITLE
Support for RADIO/DISH?

### ISSUE THREAD

**Issue by chrismacklin** [erickt/rust-zmq#205]
Any plans to expand this library to support the draft RADIO/DISH socket pattern?

**Comment by rotty** [comment]
Supporting the thread-safe socket types will require a bit of thinking, see also [this comment](https://github.com/erickt/rust-zmq/issues/250#issuecomment-494992952).

**Comment by rotty** [comment]
As these are still in draft state, I consider them out-of-scope for now; also see #122.
