### ISSUE TITLE
Allow creation with more than default IO threads

### ISSUE THREAD

**Issue by bspeice** [erickt/rust-zmq#206]
How difficult would it be to allow creation of a ZMQ context with more than one IO thread? I don't know if Rust has any special considerations, though I would expect it is just a different call to the context initialization.

**Comment by andriipatsula** [comment]
http://api.zeromq.org/3-2:zmq-ctx-set
Seems, only via unsafe { zmq_sys::zmq_ctx_set(...) } with option name ZMQ_IO_THREADS

**Comment by rotty** [comment]
As @andriipatsula noted, the `zmq` crate does not yet wrap the `zmq_ctx_set` API; this should be added, together with support for `zmq_ctx_get`. Patches welcome; in the absence of patches I'll implement support when I come around to it.
