### ISSUE TITLE
Build instructions for Windows?

### ISSUE THREAD

**Issue by bspeice** [erickt/rust-zmq#208]
I'm interested in using this for projects in Windows, and I see there's an Appveyor build going (and plenty of issues related to windows) but I have no idea how to actually install/use it. Can instructions be compiled on how to make use of this?

**Comment by rotty** [comment]
I don't have access to a Windows development environment, and have been relying on the community for making `rust-zmq` work with Windows. It is my impression that the bindings work on Windows, but there still might be rough edges. Perhaps you could attempt getting it to work and document steps needed for the benefit of other Windows developers? 

My (naive) understanding is that you'd build and install `zmq` itself, and then run `cargo build`, pointing it to the `zmq` installation as noted in the README. The details can be gleamed from [`appveyor.bat`](https://github.com/erickt/rust-zmq/blob/master/.appveyor/appveyor.bat).

**Comment by hansieodendaal** [comment]
Hi @zachlute, I am having problems building rust-zmq on Windows. 

1. I cloned the latest libzmq 4.3.2 (have to use it) from the master branch, and built it with CMake in MS Visual Studio 2017 using the `CMake -> Install -> ZeroMQ` menu option, all tests passing successfully afterwards.

1. I renamed `libzmq-mt-s-4_3_2.lib` to `zmq.lib`

1. I cloned `https://github.com/erickt/rust-zmq`, and when running `cargo build` I get a link failure:

```
C:\Users\pluto\Documents\Code\zmq\rust-zmq>cargo build
   Compiling pkg-config v0.3.14
   Compiling error-chain v0.10.0
   Compiling toml v0.2.1
   Compiling libc v0.2.50
   Compiling cfg-if v0.1.7
   Compiling bitflags v0.7.0
   Compiling log v0.4.6
   Compiling metadeps v1.1.2
   Compiling zmq-sys v0.9.0 (C:\Users\pluto\Documents\Code\zmq\rust-zmq\zmq-sys)
   Compiling zmq v0.9.0 (C:\Users\pluto\Documents\Code\zmq\rust-zmq)
error: linking with `link.exe` failed: exit code: 1120
.
.
.
= note: build_script_build-86a0088bba3cd182.59e1lonbo0hbnwk3.rcgu.o : error LNK2019: unresolved external symbol __imp_zmq_has referenced in function _ZN18build_script_build4main17h3aa1d71f1a35e113E
          C:\Users\pluto\Documents\Code\zmq\rust-zmq\target\debug\build\zmq-86a0088bba3cd182\build_script_build-86a0088bba3cd182.exe : fatal error LNK1120: 1 unresolved externals

error: aborting due to previous error

error: Could not compile `zmq`.

```

What to do?

Thanks

**Comment by hansieodendaal** [comment]
Seems I have an answer for now. This is fixed in branch `oblique:build-zmq`.

To build `rust-zmq` execute `cargo build --features static-libzmq `

To add feature to own project add 
`zmq = { git = "https://github.com/oblique/rust-zmq", branch = "build-zmq", features = ["static-libzmq"] }` under [dependencies] section in the project's Cargo.toml.

See full answer in #241.

**Comment by hansieodendaal** [comment]
See PR #249 for dynamic linking of ZeroMQ. Also added basic installation instructions.

**Comment by rotty** [comment]
@bspeice There are now some instructions in the `README` regarding building on Windows, thanks to @hansieodendaal. If something is missing, please file a new issue, with specific information on what you tried and what did not work for you.

**Comment by axil** [comment]
`https://github.com/oblique/rust-zmq` no longer exists so `cargo build --features static-libzmq` doesn't work anymore. I'm having the same error as @hansieodendaal trying to build zmq on windows as a prerequisite for [evcxr_jupyter](https://github.com/google/evcxr/tree/master/evcxr_jupyter). What is the right way to  build it nowadays?

**Comment by hansieodendaal** [comment]
I use dynamic linking of ZeroMQ as per PR #249, also used VS 2017 to compile it. Maybe you should post your error messages.

**Comment by axil** [comment]
@hansieodendaal Thank you for your reply. I've come up to the same solution: looks as if 4.0.4 version - the last compiled version I've found which comes with both .lib and .dll files - is too outdated for evcxr (as appears from the source code) and the current version (4.3.2) only comes with .dll file, but not .lib. So the only way out I see is to compile it manually.

**Comment by hansieodendaal** [comment]
Yes, that is what I did.

**Comment by axil** [comment]
Yes, I finally got it up and running. 4.3.2 version of libzmq compiled manually with cmake-gui and Visual Studio 2015 worked without any problems with evcxr_jupyter for me.

But alas, the speed of rust jupyter kernel makes it hardly usable as of today: [calculates 2+2 for 1.7 sec](https://github.com/google/evcxr/issues/52#issuecomment-521773125).
