### ISSUE TITLE
Implement io::Read & io::Write

### ISSUE THREAD

**Issue by jean-airoldie** [erickt/rust-zmq#238]
Hi,

Is there any specific reason why [`io::Read`](https://doc.rust-lang.org/std/io/trait.Read.html) and [`io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html) is not implemented for [`zmq::Socket`](https://docs.rs/zmq/0.9.0/zmq/struct.Socket.html)? I can implement `io::Read` using [zmq::Socket::recv_into](https://docs.rs/zmq/0.9.0/zmq/struct.Socket.html#method.recv_into) but not `io::Write` since there is no send method that provides the number of bytes written.

**Comment by birkenfeld** [comment]
I don't think `Read` and `Write` are a good conceptual fit for zmq sockets. They are meant for continuous streams, while zmq very much emphasizes (and guarantees) the discrete nature of each message sent.

**Comment by jean-airoldie** [comment]
They are required in order to implement the [`Stream`](https://docs.rs/tokio/0.1.14/tokio/prelude/trait.Stream.html) and [`Sink`](https://docs.rs/tokio/0.1.14/tokio/prelude/trait.Sink.html) traits and therefore fit in the general rust async ecosystem. 

While the `zmq` crates offer async operations via the polling mechanism, it makes it hard to integrate zmq sockets alongside other types of streams. For instance I have a specific use case where a server polls asynchronously both a tcp stream and a zmq socket.  This can be easily done if the socket implements `Stream` (I can simply merge the streams via `select`), but it becomes a headache otherwise.

**Comment by asonix** [comment]
I wonder if a native-rust implementation of zeromq could work with a generic stream of bytes plus a zeromq tokio-codec on top...

I agree that ZeroMQ's concept of messages conflicts with the idea of reading and writing bytes, but I do know that it's possible to use zmq with tokio, as I'm the author of [tokio-zmq](https://crates.io/crates/tokio-zmq) and [futures-zmq](https://crates.io/futures-zmq). These crates provide an abstraction of streams and futures on top of zmq, where the `Stream::Item` is a custom `Multipart` type, that represents a full multipart zmq message, whether that contains one or many individual zmq messages.

The reason I've created two crates that do the same thing is tokio-zmq uses unix-specific and tokio-specific code, while futures-zmq is OS agnostic and executor agnostic for the price of performance. The futures-zmq implementation uses a separate thread that polls a bunch of zeromq sockets, using channels to send messages back and forth to the chosen executor.

**Comment by jean-airoldie** [comment]
I wasn't aware that implementing `io::Read` could be done [without modifying the `rust-zmq` code](https://github.com/rotty/zmq-tokio/blob/master/zmq-mio/src/lib.rs#L350). And I agree that this trait shouldn't be publicly implemented since it contradicts the zmq message concept. I was just looking for a quick and dirty hack to allow integration into tokio.

**Comment by jean-airoldie** [comment]
@asonix I'll take a look at your crate.
