### ISSUE TITLE
Integrate with Rust event loop

### ISSUE THREAD

**Issue by fantix** [erickt/rust-zmq#24]
This task deadlocking issue was firstly raised here:

https://mail.mozilla.org/pipermail/rust-dev/2013-November/006365.html

where @erickt suggested that

    Or perhaps there is some way we
    can feed the ZMQ_FD of a socket to libuv to protect against task
    deadlocking.

It was not quite possible back in 2012:

http://lists.zeromq.org/pipermail/zeromq-dev/2012-March/016561.html

But it seems doable now in 2014:

https://github.com/joyent/libuv/blob/master/include/uv.h#L1164

    * The uv_poll watcher is used to watch file descriptors for readability and
    * writability, similar to the purpose of poll(2).
    *
    * The purpose of uv_poll is to enable integrating external libraries that
    * rely on the event loop to signal it about the socket status changes, like
    * c-ares or libssh2.

And it seems people are already doing so:

https://github.com/benoitc/uzmq/blob/master/uzmq/sock.py#L41

Notably, https://github.com/mozilla/rust/pull/11410 is introducing the uv_poll_t features.

**Comment by jdpage** [comment]
AFAIK, Rust no longer uses libuv, so this issue could potentially be closed.
