### ISSUE TITLE
Binding for `zmq_unbind` missing

### ISSUE THREAD

**Issue by rotty** [erickt/rust-zmq#271]
This should be quite simple to add, so I'll leave this open in case someone feels like trying their hand.

**Comment by jean-airoldie** [comment]
`zmq_unbind` doesnt do anything different than `zmq_disconnect`. However, from what I understand, this might change in the future without notice.

**Comment by rotty** [comment]
Indeed, quoting the `zmq_unbind` manpage:

> Note that while the implementation is similar to zmq_disconnect(), the semantics are different and the two functions should not be used interchangeably. Bound sockets should be unbound, and connected sockets should be disconnected.

**Comment by jean-airoldie** [comment]
Yes, but if you actually look at the implementation, its the same.
https://github.com/zeromq/libzmq/blob/0858038367d43665221b8ab701471ba8d9b232bd/src/zmq.cpp#L339.
