### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by smdcw** [erickt/rust-zmq#341]
There have been some helpful additions to master since 0.9.2 was released. Are there any plans to release a new version in the near future?

**Comment by MarijnS95** [comment]
This crate is effectively abandoned. We've re-released it with improvements and other outstanding PRs merged as https://crates.io/crates/zmq2. See also https://github.com/erickt/rust-zmq/pull/339#issuecomment-1086675504.

**Comment by clintfred** [comment]
@Jasper-Bekkers It looks like 0.10 is getting close to release. Not trying to press, just looking for an update.

**Comment by Jasper-Bekkers** [comment]
We released 0.10.0 today, hope you like it. It's been updated to use latest stable upstream zmq release as and it removes the cmake dependency.
