### ISSUE TITLE
rust-zmq does not build with nightly

### ISSUE THREAD

**Issue by flo-dhalluin** [erickt/rust-zmq#47]
>src/zmq/lib.rs:30:13: 30:33 error: expected constant expr for vector length: non-constant path in constant expr
>src/zmq/lib.rs:30 type Msg_ = [c_char, ..MsgSize_];
>                              ^~~~~~~~~~~~~~~~~~~~

Submitted pull request #46

**Comment by jedisct1** [comment]
rust-zmq was updated, so this issue can probably be closed now. Thanks!
