### ISSUE TITLE
Will zeromq V2 be supported?

### ISSUE THREAD

**Issue by amosbird** [erickt/rust-zmq#62]
I have a legacy project which needs to use zeromq 2.1.7. Is it possible to support V2 ?

**Comment by erickt** [comment]
Hello! Do you know how compatible the libzmq API 4.x is with 2.x? If it's compatible, then I would assume you could use it assuming you don't use APIs that are 3.x and above. To be safe, we could add some feature flags that hide the functionality you can't use.

**Comment by Asmod4n** [comment]
https://github.com/zeromq/czmq is compatible all the way down to 2.* and up to latest libzmq master, so it should be possible, take a look how they do it :)
