### ISSUE TITLE
Should Context::socket() be &self instead of &mut self?

### ISSUE THREAD

**Issue by jdpage** [erickt/rust-zmq#64]
So I understand that Context::socket() changes the state of the context, which is presumably the idea behind making it &mut self. That said, it's entirely safe for multiple threads to call socket() on the same context, so it should be safe to make it &self.

My motivation for suggesting this is that, right now, the suggested method for sharing a context between threads is to use an Arc<T> pointer. But once you have the context in an Arc pointer, there doesn't seem to be a way to get a hold of a mutable pointer to it, so you can't make any more sockets. Arc::make_unique() is unavailable, since Context doesn't implement Clone, and that would do the wrong thing anyway.

**Comment by jdpage** [comment]
As a further note, this would allow one to dispense with Arc entirely. Since Context is Sync, it can be aliased across threads safely anyway, and if Context::socket() takes &self, there's no reason to ever have a mutable pointer to it.

**Comment by blaenk** [comment]
I agree.

**Comment by rotty** [comment]
This should be addressed by merging #96.
