### ISSUE TITLE
Socket and PollItem should be Send

### ISSUE THREAD

**Issue by apoelstra** [erickt/rust-zmq#67]
Both `Socket` and `PollItem` are safe to be `Send` (they are not automatically because they contain `c_void *` pointers, but this is fine since neither references any other data). Neither is allowed to be `Sync`, see the loud warning under "Thread Safety" in http://api.zeromq.org/3-2:zmq-socket

**Comment by rotty** [comment]
In current master, `Socket` is already `Send` (see commit 3687be1). I don't think `PollItem` can be simply made `Send`, as it references a `Socket`. I'm also not clear if there is a real use-case for marking `PollItem` as `Send`. Could you provide an example?

**Comment by apoelstra** [comment]
No, I have not used rust-zmq since filing this bug. I don't remember exactly how I had intended to use it.

**Comment by rotty** [comment]
OK, I'll close this then.
