### ISSUE TITLE
Can PUB/SUB use topic filtering?

### ISSUE THREAD

**Issue by Densaugeo** [erickt/rust-zmq#72]
In the Node.js version of zmq, when publishing a message on a PUB socket you can set a topic and a message, and the SUB socket filters them by topic. However, when sending a message from a PUB socket using this crate, the first argument of .send is set as the topic and the message is blank. Is there a way to send a message body as well with this crate?

**Comment by erickt** [comment]
Yes it should support that. rust-zmq is a pretty thin wrapper around libzmq, so you can refer to it's documentation on [topic filtering](http://zguide.zeromq.org/page%3aall#Pub-Sub-Message-Envelopes). In short, you should publish with messages like:

```rust
socket.send(b"my-topic", zmq::SNDMORE).unwrap();
socket.send(b"", zmq::SNDMORE).unwrap();
socket.send(b"my-body", 0).unwrap();
```

**Comment by Densaugeo** [comment]
Got a chance to work on my project again and the filtering is working now, thanks!

I found that this worked:

~~~
socket.send(b"my-topic", zmq::SNDMORE).unwrap();
socket.send(b"my-body", 0).unwrap();
~~~

Using the blank line in the middle caused the message body to be blank.
