### ISSUE TITLE
There is some possibility to develop encryption for messages exchanged in zmq.rs??

### ISSUE THREAD

**Issue by dzobbe** [erickt/rust-zmq#74]

**Comment by rotty** [comment]
I don't quite get your question -- are you asking about support for zmq_curve? If so, it seems rust-zmq has bindings for that, but I haven't played with them yet, so I can't tell (myself being just a recent rust-mzq user).

**Comment by rotty** [comment]
As was a question (not an "issue" per se), and I've tried to answer it, plus there has been no response to my request on clarification, I'm closing this now.
