### ISSUE TITLE
Why &str instead of String?

### ISSUE THREAD

**Issue by petehayes102** [erickt/rust-zmq#78]
This is probably my ignorance, but why are you using a str ref for methods like socket.connect instead of String? I normally derive my connection strings from a static protocol and a variable endpoint address, e.g. "ipc://" + addr. As far as I'm aware, you can't concatenate two static strings and end up with a static string. And as String.to_str() is not yet stable, wouldn't it make sense to be able to pass a String object instead of a &str?

With the current implementation, how would you implement something like this:

let conn = format!("ipc://{}", socket_path);
socket.connect(conn).unwrap();

Ta!

**Comment by jedisct1** [comment]
```rust
socket.connect(&conn).unwrap();
```

Using `&str` whenever possible avoids copies.

**Comment by petehayes102** [comment]
Damn...and when I thought I'd got the dumbest questions out of the way. Cheers mate.
