### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by Ginurx** [erickt/rust-zmq#83]
## Those error codes are only meaningful under *nix. Latest libc does not define them on Win.

src\lib.rs:126:23: 126:35 error: unresolved name `libc::EACCES` [E0425]
src\lib.rs:126     EACCES          = libc::EACCES as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:126:23: 126:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:127:23: 127:39 error: unresolved name `libc::EADDRINUSE` [E0425]
src\lib.rs:127     EADDRINUSE      = libc::EADDRINUSE as isize,
                                     ^~~~~~~~~~~~~~~~
src\lib.rs:127:23: 127:39 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:128:23: 128:35 error: unresolved name `libc::EAGAIN` [E0425]
src\lib.rs:128     EAGAIN          = libc::EAGAIN as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:128:23: 128:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:129:23: 129:34 error: unresolved name `libc::EBUSY` [E0425]
src\lib.rs:129     EBUSY           = libc::EBUSY as isize,
                                     ^~~~~~~~~~~
src\lib.rs:129:23: 129:34 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:130:23: 130:41 error: unresolved name `libc::ECONNREFUSED` [E0425]
src\lib.rs:130     ECONNREFUSED    = libc::ECONNREFUSED as isize,
                                     ^~~~~~~~~~~~~~~~~~
src\lib.rs:130:23: 130:41 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:131:23: 131:35 error: unresolved name `libc::EFAULT` [E0425]
src\lib.rs:131     EFAULT          = libc::EFAULT as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:131:23: 131:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:132:23: 132:34 error: unresolved name `libc::EINTR` [E0425]
src\lib.rs:132     EINTR           = libc::EINTR as isize,
                                     ^~~~~~~~~~~
src\lib.rs:132:23: 132:34 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:133:23: 133:41 error: unresolved name `libc::EHOSTUNREACH` [E0425]
src\lib.rs:133     EHOSTUNREACH    = libc::EHOSTUNREACH as isize,
                                     ^~~~~~~~~~~~~~~~~~
src\lib.rs:133:23: 133:41 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:134:23: 134:40 error: unresolved name `libc::EINPROGRESS` [E0425]
src\lib.rs:134     EINPROGRESS     = libc::EINPROGRESS as isize,
                                     ^~~~~~~~~~~~~~~~~
src\lib.rs:134:23: 134:40 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:135:23: 135:35 error: unresolved name `libc::EINVAL` [E0425]
src\lib.rs:135     EINVAL          = libc::EINVAL as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:135:23: 135:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:136:23: 136:35 error: unresolved name `libc::EMFILE` [E0425]
src\lib.rs:136     EMFILE          = libc::EMFILE as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:136:23: 136:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:137:23: 137:37 error: unresolved name `libc::EMSGSIZE` [E0425]
src\lib.rs:137     EMSGSIZE        = libc::EMSGSIZE as isize,
                                     ^~~~~~~~~~~~~~
src\lib.rs:137:23: 137:37 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:138:23: 138:41 error: unresolved name `libc::ENAMETOOLONG` [E0425]
src\lib.rs:138     ENAMETOOLONG    = libc::ENAMETOOLONG as isize,
                                     ^~~~~~~~~~~~~~~~~~
src\lib.rs:138:23: 138:41 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:139:23: 139:35 error: unresolved name `libc::ENODEV` [E0425]
src\lib.rs:139     ENODEV          = libc::ENODEV as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:139:23: 139:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:140:23: 140:35 error: unresolved name `libc::ENOENT` [E0425]
src\lib.rs:140     ENOENT          = libc::ENOENT as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:140:23: 140:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:141:23: 141:35 error: unresolved name `libc::ENOMEM` [E0425]
src\lib.rs:141     ENOMEM          = libc::ENOMEM as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:141:23: 141:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:142:23: 142:37 error: unresolved name `libc::ENOTCONN` [E0425]
src\lib.rs:142     ENOTCONN        = libc::ENOTCONN as isize,
                                     ^~~~~~~~~~~~~~
src\lib.rs:142:23: 142:37 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:143:23: 143:37 error: unresolved name `libc::ENOTSOCK` [E0425]
src\lib.rs:143     ENOTSOCK        = libc::ENOTSOCK as isize,
                                     ^~~~~~~~~~~~~~
src\lib.rs:143:23: 143:37 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:144:23: 144:35 error: unresolved name `libc::EPROTO` [E0425]
src\lib.rs:144     EPROTO          = libc::EPROTO as isize,
                                     ^~~~~~~~~~~~
src\lib.rs:144:23: 144:35 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation
src\lib.rs:145:23: 145:44 error: unresolved name `libc::EPROTONOSUPPORT` [E0425]
src\lib.rs:145     EPROTONOSUPPORT = libc::EPROTONOSUPPORT as isize,
                                     ^~~~~~~~~~~~~~~~~~~~~
src\lib.rs:145:23: 145:44 help: run `rustc --explain E0425` to see a detailed ex                                                                    planation

**Comment by erickt** [comment]
This has been fixed in #124, and should be in the next release of our crate. We still can't say we officially support things until we fix all the bugs in #125 though.
