### ISSUE TITLE
Support for ZMQ_STREAM socket type

### ISSUE THREAD

**Issue by karec** [erickt/rust-zmq#95]
Is it planned to add support for `ZMQ_STREAM` sockets ? 

http://api.zeromq.org/4-2:zmq-socket#toc17

**Comment by rotty** [comment]
Definitely, also for the new `ZMQ_CLIENT` and `ZMQ_SERVER` added in libzmq 4.2. However, I don't know when I'll come around to implementing support for them. Pull requests welcome, however!
